const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
let selected=currentStory.entry,history=[],visited=new Set([currentStory.entry]),edgesVisited=new Set(),arrival='',zoom=.85,variantState={};
const NS='http://www.w3.org/2000/svg',W=currentStory.mapWidth,H=currentStory.mapHeight,NW=205,NH=92;
const svg=$('#graph'),scroll=$('#map-scroll');
svg.setAttribute('viewBox',`0 0 ${W} ${H}`);
$('#work-title').textContent=currentStory.series+' / '+currentStory.title;
$('#work-count').textContent=(Object.keys(nodes).length-1)+'개 장면 · 조건 분기';
$('.stages').innerHTML=currentStory.stages.map(s=>`<button data-jump="${s.node}">${esc(s.label)}</button>`).join('');
const edgeData=[];
Object.values(nodes).forEach(node=>node.choices.forEach((choice,index)=>{edgeData.push({from:node.id,to:choice.to,condition:choice.condition,index,alt:false});if(choice.alternate)edgeData.push({from:node.id,to:choice.alternate.to,condition:choice.alternate.label,index,alt:true});}));
function sEl(tag,attrs={},text){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));if(text!==undefined)e.textContent=text;return e;}
function edgeLabel(e){if(e.from===7)return e.to===8?'총기 + 탄약':e.to===23?'캐리':e.to===24?'괴상함 · 일반':e.to===25?'괴상함 · 성공':'총기 · 탄약 없음';if(e.from===9)return e.to===13?'사격술 · 성공':'사격술 · 실패';if(e.from===10)return e.to===27?'item_gun:':'총기 미보유';if(e.from===13)return e.to===19?'능청스러움':e.to===21?'괴상함':e.to===28?'선불 보상':'쥐고기';return '';}
function buildGraph(){svg.innerHTML='';const defs=sEl('defs');const marker=sEl('marker',{id:'arrow',viewBox:'0 0 10 10',refX:9,refY:5,markerWidth:5,markerHeight:5,orient:'auto-start-reverse'});marker.append(sEl('path',{d:'M 0 0 L 10 5 L 0 10 z',fill:'#8b819f'}));defs.append(marker);svg.append(defs);
const layers=sEl('g');svg.append(layers);
edgeData.forEach(e=>{let [x1,y1]=positions[e.from],[x2,y2]=positions[e.to];x1+=NW/2;y1+=NH;x2+=NW/2;let d;
if(e.to==='F'){const lane=e.from===1?25:e.from===12?15:e.from===20?1240:e.from===28?230:1215;d=`M ${x1} ${y1} C ${lane} ${y1+35}, ${lane} ${y2-60}, ${x2} ${y2}`;}
else if(e.from===13&&e.to===28){d=`M ${x1} ${y1} C 460 ${y1+80}, 460 ${y2-100}, ${x2} ${y2}`;}
else if((e.from===14||e.from===22)&&[15,16,17,18].includes(e.to)){const lane=e.from===14?2160:2190;d=`M ${x1} ${y1} C ${x1} ${lane}, ${x2} ${lane}, ${x2} ${y2}`;}
else {const mid=(y1+y2)/2;d=`M ${x1} ${y1} C ${x1} ${mid}, ${x2} ${mid}, ${x2} ${y2}`;}
const p=sEl('path',{d,class:'edge'+(e.condition?' conditional':'')+(e.to==='F'?' ending':''),'marker-end':'url(#arrow)'});e.element=p;layers.append(p);
const lab=edgeLabel(e);if(lab){const ly=e.from===7?(e.to===26?1140:1275):e.from===13?1818:(y1+y2)/2-5;const lx=e.from===7?(e.to===26?240:x2):e.from===13?(e.to===28?460:x2):(x1+x2)/2;layers.append(sEl('text',{x:lx,y:ly,'text-anchor':'middle',class:'edge-label'},lab));}});
currentStory.mapLabels.forEach(([t,y])=>svg.append(sEl('text',{x:38,y:y-20,class:'stage-label'},t)));
Object.values(nodes).forEach(node=>{const [x,y]=positions[node.id];const group=sEl('g',{class:'scene',transform:`translate(${x},${y})`,tabindex:0,role:'button','aria-label':`${node.id}번 ${node.title}`,'data-id':node.id});group.append(sEl('rect',{class:'main',width:NW,height:NH,rx:9}));group.append(sEl('text',{x:15,y:22,class:'node-id'},node.id==='F'?'END':`SCENE ${String(node.id).padStart(2,'0')}`));group.append(sEl('text',{x:15,y:49,class:'node-title'},node.title));const meta=node.id===27?'item_gun: · 총기 보유':node.choices.length>1?`${node.choices.length}개 선택지`:node.choices[0]?.alternate?'조건에 따른 2개 경로':node.phase==='결말'?'결말':node.id==='F'?'다른 경로 살펴보기':'이야기 진행';group.append(sEl('text',{x:15,y:75,class:'node-meta'},meta));group.addEventListener('click',()=>select(node.id));group.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select(node.id);}});svg.append(group);});}
function updateGraph(){svg.querySelectorAll('.scene').forEach(el=>{const id=el.dataset.id;el.classList.toggle('selected',String(selected)===id);el.classList.toggle('visited',visited.has(id==='F'?'F':Number(id)));el.setAttribute('aria-pressed',String(String(selected)===id));});edgeData.forEach(e=>{e.element.classList.toggle('near',String(e.from)===String(selected)||String(e.to)===String(selected));e.element.classList.toggle('visited',edgesVisited.has(`${e.from}-${e.to}`));});document.querySelectorAll('[data-jump]').forEach(b=>b.classList.toggle('active',nodes[Number(b.dataset.jump)].phase===nodes[selected].phase));}
function variantsOf(text){const regex=/\$?\{_getItemCount\('([^']+)'\)([<>])(\d+)\?'([^']*)':'([^']*)'\}/g;return Array.from(text.matchAll(regex),m=>({raw:m[0],item:m[1],operator:m[2],value:m[3],yes:m[4],no:m[5]}));}
function formatText(text,scope){let out='',last=0;const regex=/\$?\{_getItemCount\('([^']+)'\)([<>])(\d+)\?'([^']*)':'([^']*)'\}/g;let m,index=0;while((m=regex.exec(text))){out+=esc(text.slice(last,m.index));const chosen=variantState[scope+'-'+index]??false;out+=`<span class="inline-variant">${esc(chosen?m[4]:m[5])}<span class="variant-marker">[조건 ${index+1}]</span></span>`;last=regex.lastIndex;index++;}out+=esc(text.slice(last));return out.replace(/\$\{_getLocalVariable\(&#39;예삐전 날짜&#39;\)\}/g,'<span class="variable">[예삐전 날짜]</span>');}
function variantDetails(text,scope){const variants=variantsOf(text);if(!variants.length)return '';return `<details class="variants"><summary>조건별 문장 보기 · ${variants.length}개</summary>${variants.map((v,i)=>`<div class="variant-item"><strong>${i+1}. ${esc(v.item)} ${v.operator==='>'&&v.value==='0'?'보유':esc(v.operator+' '+v.value)}</strong><div class="variant-row"><span>충족 시</span><div><p>${esc(v.yes.trim()||'(추가 문장 없음)')}</p><button data-variant="${scope}-${i}" data-value="true">이 문장으로 읽기</button></div></div><div class="variant-row"><span>미충족</span><div><p>${esc(v.no.trim()||'(추가 문장 없음)')}</p><button data-variant="${scope}-${i}" data-value="false">이 문장으로 읽기</button></div></div></div>`).join('')}</details>`;}
function renderReader(){const node=nodes[selected],scope='body-'+selected;const rawChoices=node.choices.map(ch=>`${ch.to} · ${ch.text}${ch.condition?'\n조건: '+ch.condition:''}${ch.effect?'\n효과: '+ch.effect:''}${ch.alternate?'\n추가 경로: '+ch.alternate.to+' · '+ch.alternate.label:''}`).join('\n\n');$('#reader').innerHTML=`<article class="reader-content"><div class="scene-kicker">${node.id==='F'?'END OF ROUTE':`SCENE ${String(node.id).padStart(2,'0')}`}<span class="phase-badge">${node.phase}</span></div><h2 class="scene-heading">${esc(node.title)}</h2>${history.length?`<div class="trail">읽어온 장면 ${history.slice(-7).map((h,i)=>`<button data-history="${Math.max(0,history.length-7)+i}">${String(h.id).padStart(2,'0')}</button>`).join(' › ')} › ${String(selected).padStart(2,'0')}</div>`:''}${node.entry?`<div class="entry-note">${esc(node.entry)}</div>`:''}${arrival?`<div class="arrival">선택 결과 · ${esc(arrival)}</div>`:''}<div class="scene-text">${node.body.split(/\n\n/).map(p=>`<p class="${p.trim().startsWith('“')?'dialogue':''}">${formatText(p,scope)}</p>`).join('')}</div>${variantDetails(node.body,scope)}${node.choices.length?`<div class="choice-header"><h3>선택지</h3><span>선택하면 다음 장면으로</span></div><div class="choices">${node.choices.map((ch,i)=>`<div class="choice">${ch.alternate?'<div class="choice-main">':`<button class="choice-main" data-choice="${i}">`}<div class="choice-top"><span>${formatText(ch.text,`choice-${selected}-${i}`)}</span><span class="choice-arrow">${ch.alternate?'⑂':'↗'}</span></div>${ch.condition||ch.effect?`<div class="choice-meta">${ch.condition?`<span class="condition">${esc(ch.alternate?.kind==='item'?'item_gun: · 총기 보유 여부':ch.condition)}</span>`:''}${ch.effect?`<span class="effect">${esc(ch.effect)}</span>`:''}</div>`:''}${ch.alternate?`</div><div class="judgment"><button data-choice="${i}">${esc(ch.alternate.base)} <span class="destination">→ ${ch.to}</span></button><button data-choice="${i}" data-alt="true">${esc(ch.alternate.label)} <span class="destination">→ ${ch.alternate.to}</span></button></div>`:'</button>'}</div>${variantDetails(ch.text,`choice-${selected}-${i}`)}`).join('')}</div>`:`<div class="end-actions"><button id="end-restart">처음부터 읽기</button><button id="end-reward">보상 분기로 돌아가기</button></div>`}${selected!=='F'?`<details class="source"><summary>대사 원문 · 분기 데이터</summary><pre>${esc(node.id+':: '+node.body)}${node.entry?'\n\n진입 조건: '+esc(node.entry):''}</pre><pre>${esc(rawChoices)}</pre></details>`:''}</article>`;
$('#back').disabled=!history.length;
$('#reader').querySelectorAll('[data-choice]').forEach(b=>b.addEventListener('click',()=>{const ch=node.choices[Number(b.dataset.choice)],to=b.dataset.alt?ch.alternate.to:ch.to;edgesVisited.add(`${selected}-${to}`);select(to,ch.effect);}));
$('#reader').querySelectorAll('[data-variant]').forEach(b=>b.addEventListener('click',()=>{const top=$('#reader-scroll').scrollTop;variantState[b.dataset.variant]=b.dataset.value==='true';renderReader();$('#reader').querySelectorAll('.variants').forEach(d=>d.open=true);$('#reader-scroll').scrollTop=top;}));
$('#reader').querySelectorAll('[data-history]').forEach(b=>b.addEventListener('click',()=>{const ix=Number(b.dataset.history),h=history[ix];history=history.slice(0,ix);select(h.id,h.arrival,false);}));
$('#end-restart')?.addEventListener('click',restart);$('#end-reward')?.addEventListener('click',()=>select(currentStory.rewardNode));}
function select(id,effect='',push=true){if(!nodes[id])return;if(push&&String(id)!==String(selected))history.push({id:selected,arrival});selected=id;arrival=effect;visited.add(id);renderReader();updateGraph();$('#reader-scroll').scrollTop=0;focusNode();if(window.innerWidth<=760)$('#reader').scrollIntoView({behavior:'smooth',block:'start'});}
function focusNode(){const [x,y]=positions[selected];scroll.scrollTo({left:(x+NW/2)*zoom-scroll.clientWidth/2,top:(y+NH/2)*zoom-scroll.clientHeight/2,behavior:'auto'});}
function setZoom(z,focus=true){zoom=Math.max(.1,Math.min(1.5,z));$('#map-canvas').style.width=W*zoom+'px';$('#map-canvas').style.height=H*zoom+'px';$('#zoom-label').textContent=Math.round(zoom*100)+'%';if(focus)focusNode();}
function restart(){history=[];visited=new Set([currentStory.entry]);edgesVisited.clear();arrival='';variantState={};select(currentStory.entry,'',false);}
$('#back').addEventListener('click',()=>{const h=history.pop();if(h)select(h.id,h.arrival,false);});$('#restart').addEventListener('click',restart);$('#zoom-in').addEventListener('click',()=>setZoom(zoom+.15));$('#zoom-out').addEventListener('click',()=>setZoom(zoom-.15));$('#fit').addEventListener('click',()=>{setZoom(Math.min(scroll.clientWidth/W,scroll.clientHeight/H),false);scroll.scrollTo(0,0);});$('#focus').addEventListener('click',()=>setZoom(.85));document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>select(Number(b.dataset.jump))));
let drag=null;scroll.addEventListener('pointerdown',e=>{if(e.target.closest('.scene')||e.pointerType==='touch')return;drag={x:e.clientX,y:e.clientY,left:scroll.scrollLeft,top:scroll.scrollTop};scroll.setPointerCapture(e.pointerId);scroll.classList.add('dragging');});scroll.addEventListener('pointermove',e=>{if(drag){scroll.scrollLeft=drag.left-(e.clientX-drag.x);scroll.scrollTop=drag.top-(e.clientY-drag.y);}});function stopDrag(){drag=null;scroll.classList.remove('dragging');}scroll.addEventListener('pointerup',stopDrag);scroll.addEventListener('pointercancel',stopDrag);
buildGraph();renderReader();updateGraph();setZoom(.85);window.addEventListener('resize',focusNode);
